server:
  port: 9000
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bitai
    driver-class-name: org.mariadb.jdbc.Driver
    username: bitai
    password: 456123
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

# server:
#   port: 8080

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/bitai?serverTimezone=UTC&useSSL=false
#     username: bitai
#     password: 456123
#     driver-class-name: com.mysql.cj.jdbc.Driver